# Generated by Django 5.2.4 on 2025-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('aba_pay', 'ABA Pay'), ('wing', 'Wing')], max_length=20),
        ),
    ]
