# Generated by Django 5.2.4 on 2025-07-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_qty'),
        ('products', '0001_initial'),
    ]

    operations = [
        # Remove the Product and Category models from store app
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
